# Chart testing configuration for ct (chart-testing)
target-branch: main
chart-dirs:
  - deploy/helm
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
helm-extra-args: --timeout 600s
check-version-increment: true
debug: true