title: "LLM Proxy"
description: "Open‑source reverse proxy for LLM APIs with withering tokens, management UI and observability"
url: "https://sofatutor.github.io"
baseurl: "/llm-proxy"

# Use the Just the Docs remote theme for a modern documentation site.
# See: https://just-the-docs.com/ for theme details.
remote_theme: just-the-docs/just-the-docs
color_scheme: light
search_enabled: true

# Plugins remain for additional metadata (SEO, etc.)
markdown: kramdown
plugins:
  - jekyll-seo-tag
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.9.0"

# Files and directories to exclude from the build
exclude:
  - vendor
  - node_modules
  - README.md
  - PLAN.md
  - CONTRIBUTING.md
  - LICENSE
  - issues/
  - done/

# Auxiliary links shown in the top navigation bar
aux_links:
  "LLM Proxy on GitHub": "https://github.com/sofatutor/llm-proxy"

# The navigation sidebar is built automatically from your pages.
# To control the order of pages, add `nav_order` and `title` in each page's front matter.
