title: "LLM Proxy"
description: "Open-source reverse proxy for LLM APIs with withering tokens, management UI, and observability"
url: "https://sofatutor.github.io"
baseurl: "/llm-proxy"

# GitHub Pages defaults
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag

# Build settings
exclude:
  - vendor
  - node_modules
  - README.md
  - PLAN.md
  - CONTRIBUTING.md
  - LICENSE
  - issues/
  - done/

# Minima theme configuration
minima:
  skin: auto
  nav_pages:
    - index.md
    - features.md
    - screenshots.md
    - quickstart.md
    - cli-reference.md
    - architecture.md
    - contributing.md
    - coverage.md
    - github.md


