name: Docker

on:
  push:
    branches: [ main, docker/phase-6-docker-optimization-ghcr ]
    tags: [ 'v*' ]

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true
      
      - name: Verify dependencies
        run: |
          go mod verify
          go mod tidy
          git diff --exit-code -- go.mod go.sum
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build (branches/PR) - linux/amd64
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push (main/tags) - linux/amd64,linux/arm64
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Pull pushed image and tag for Makefile
        if: github.event_name != 'pull_request'
        run: |
          # Use sanitized branch tag (ref name with slashes replaced by '-')
          BRANCH_TAG="${GITHUB_REF_NAME//\//-}"
          echo "Pulling ghcr.io/${{ github.repository }}:${BRANCH_TAG}"
          docker pull ghcr.io/${{ github.repository }}:${BRANCH_TAG}
          docker tag ghcr.io/${{ github.repository }}:${BRANCH_TAG} llm-proxy:latest

      - name: Smoke test using Makefile (run + health)
        if: github.event_name != 'pull_request'
        run: |
          make docker-smoke
        env:
          MANAGEMENT_TOKEN: smoke-token

      - name: Stop container (cleanup)
        if: always()
        run: make docker-stop